version: 0.1
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Dependencies......."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package......."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to s3........"
      - aws s3 cp deployment_package.zip s3://s3-aws-de-cicd/
      - echo "Creating lambda function via s3......."
      - aws lambda create-function --function-name github-to-lambda-cicd --runtime python3.11 --role arn:aws:iam::891376943331:role/aws-de-lambda-role --handler lambda_function.lambda_handler --code S3Bucket=s3-aws-de-cicd,S3Key=deployment_package.zip
      - echo "Deployment complete............."
